### ISSUE TITLE
cannot run your code from your article 

### ISSUE THREAD

**Issue by ayueme** [mlr-org/mlr3gallery#115]
I copied you code from this article [Practical Tuning Series - Build an Automated Machine Learning System](https://mlr3gallery.mlr-org.com/posts/2021-03-11-practical-tuning-series-build-an-automated-machine-learning-system/) ,
when I run this code: `graph_learner$param_set$values$branch.selection = to_tune(c("kknn", "svm", "ranger"))`, 
I got this error: 
`Error in self$assert(xs) : 
Assertion on 'xs' failed: branch.selection: tune token invalid: to_tune(c("kknn", "svm", "ranger")) generates points that are not compatible with param selection.
Bad value:
[1] "kknn"
Parameter:
          id    class lower upper levels        default
1: selection ParamInt     1     3        <NoDefault[3]>.`
How should I correct it ?
Thank you.

**Comment by pat-s** [comment]
There seem to be some issues with this post right now, we're trying to resolve it. See also #116

**Comment by be-marc** [comment]
Thanks for reporting. Fixed by latest mlr3 github version.
