### ISSUE TITLE
Publish on r-bloggers

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3gallery#36]
We should cherry-pick some posts from the gallery and publish them on r-bloggers via the mlr3 blog (maybe after polishing them a bit). Additionally, we should try to get the gallery into r-bloggers and r-weekly so that new posts are automatically published there.

@berndbischl your 2 cents?

**Comment by berndbischl** [comment]
i dont know. i was kinda against having the gallery already as a separate "docs" system / place. 
(I really like it now!)
but making now THAT totally redundant again? i am against that I think.
if we can get the posts automatically into r-bloggers: great

**Comment by pat-s** [comment]
Where do we want to go with mlr-org.com? Actually this is the main site (and linked to r-bloggers already) and does not see any posts lately.

**Comment by mllg** [comment]
I'm okay with not linking mrl3gallery, but we should announce noteworthy gallery posts in the blog.
