### ISSUE TITLE
gallery deployment setup suboptimal

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3gallery#44]
ok, its kinda 2 things

1) it is a bit unclear for a new or edited post which files should be pushed where

2) I don't understand why we require to push so many files in general

this is from a current edit, where I simply fixed some typos

        modified:   _posts/2020-03-18-iris-mlr3-basics/2020-03-18-iris-mlr3-basics.Rmd
        modified:   _posts/2020-03-18-iris-mlr3-basics/2020-03-18-iris-mlr3-basics.html
        modified:   docs/index.html
        modified:   docs/index.xml
        modified:   docs/posts/2020-03-18-iris-mlr3-basics/index.html
        modified:   docs/posts/posts.json
        modified:   docs/sitemap.xml

Analyis:

- I am touching 7 (!) files, I should push one? The RMD
- The HTML is now included in there twice? I am not even sure if that's our current setup. 
IMHO it should be in the PR zero times. Even if we for some reason require the user to push the HTML, it should be documented in the README where. (the readme mentions docs, but not if the HTML should also be in _posts)
- I am touching global files. Thats an invitation to "merge conflict hell"? Especially as we are not merging PRs super fast here

--->

Why don't we have a normal "deploy setup" with travis? the user pushes the RMD only, travis builds the rest. and i guess then travis needs to self-push the compiled HTML under "docs
"

**Comment by pat-s** [comment]
There is no deployment happening right now. CI just renders the Rmds but does not build the website.

We can build and deploy the website via CI if we want, then we can only commit the Rmd. I did not expect manual staging of contents in `docs/` to cause that many issues...

You can see what is being changed in detail if you look at the diff of all files. This is just due to the nature of distill.

Anyways, let's outsource deployment to CI so that only the Rmd needs to be committed..

**Comment by berndbischl** [comment]
I mean, I dont want to overcomplicate this, the current system would work too, I guess (?).
Modulo at least some missing sentences in the README.

But I think deploying via CI just seems cleaner. And it's probably better to sort this out now, than later.

**Comment by pat-s** [comment]
> I mean, I dont want to overcomplicate this, the current system would work too, I guess (?).

Not sure. I guess there are too many people contributing to this repo which are on the edge of running into conflicts continuously with the current system.
I think a "commit only Rmd" is the most safe one in the long term. I do not want to force-push clean all PRs all the time ;)

Already testing in a branch. Should be ready tomorrow.

**Comment by berndbischl** [comment]
then we agree + perfect

**Comment by pat-s** [comment]
Should be better now with https://github.com/mlr-org/mlr3gallery/commit/b12e3b234e5a7ab7e9d9fe4a63c51af307a18013, let's see how it goes in the next days.
