### ISSUE TITLE
Add option to NOT render a post, but instead have the user upload rendered html

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3gallery#56]
A frequently occurring situation is that we want to use datasets from Kaggle, 
but we can not easily access them during CI because getting them requires logging in to Kaggle and accepting competition rules.
In this case, we might want to allow people to simply upload the full, rendered HTML (and state in the text how to get the data). 

Could this be solved via an additional flag in the post's YAML header?

This also holds for other cases, where building the post would require a lot of additional setup / overhead (e.g. running something on a GPU which is not available on CI).

**Comment by be-marc** [comment]
Rendered posts can be added to the `_static` folder now. See section "Static posts" in the readme file.
