### ISSUE TITLE
check and fix posts using german_credit task

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3gallery#59]
related to mlr-org/mlr3#514

affects the following posts:

- [x]  2020-03-11-basics-german-credit (runs fine because no specific use of the internal structure of variables is made here) 

- [x]  2020-03-11-mlr3pipelines-tutorial-german-credit (should run fine but is no longer very sensible because now there are only 3 integer features being used and the filter is using 3 features, therefore needs some minor changes)

- [x]  2020-03-11-mlr3tuning-tutorial-german-credit (runs fine but uses data from here https://github.com/mlr-org/mlr-outreach/raw/master/2019_madrid/mlr3tuning/randomsearch_3600.rds which uses the old `german_credit`; not sure whether other outreach files need to be changed/looked at as well)

- [x] 2020-03-30-stratification-blocking (runs fine, no changes needed)

- [x]  2020-01-31-encode-factors-for-xgboost (needs minor wording changes because there is now more than one ordered factor and `unemployment_duration` is now a factor)

**Comment by mllg** [comment]
All merged, thanks for the PRs.
