### ISSUE TITLE
Deployment: Install packages from yaml frontmatter

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3gallery#6]
Each document has a YAML front-matter that lists the needed packages. These should be automatically installed by whatever deploy method we are using.
It seems redundant to put these in the fictitious DESCRIPTION file.

**Comment by pat-s** [comment]
I don't see the advantage for this custom way of querying/installing dependencies.

Many functions operate on the DESCRIPTION file. Also, to render and deploy all posts we need all packages anyhow.
So what is the advantage of (possibly) writing custom code to extract the packages from the YAML frontmatter just for CI purposes?

**Comment by mllg** [comment]
The main advantage was to keep the list of dependencies in the DESCRIPTION short. No need to install survival packages to render a geospatial post, right?

Well, apparently the information has been deleted already, so I guess I can close here?
