### ISSUE TITLE
Tuning usecase uses outdated API

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr3gallery#66]
https://mlr3gallery.mlr-org.com/posts/2020-03-11-mlr3tuning-tutorial-german-credit/

`TunerInstance` is now `TunerInstanceSingleCrit` and some other arguments have changed as well, (`terms` became `trm`, `measures` -> `measure`, etc.). 

The gallery should be checked after each API change, otherwise it's very confusing for people trying to learn mlr3 from these examples.

**Comment by mllg** [comment]
Fixed this.
