### ISSUE TITLE
Render large data tables as HTML

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3gallery#69]
There are packages for this, we should use them for larger tables.

**Comment by mllg** [comment]
@be-marc can you give it a try?

**Comment by be-marc** [comment]
PR #102 is going to use the following rules for tables:

1. Include our custom css file in the YAML section which reduces the font size of tables.

```r
output:
  distill::distill_article:
    self_contained: false
    css: ../../custom.css
```

1. Limit tables to important columns and rows.

```r
as.data.table(bmr)[, .(learner_id, classif.ce)]

head(as.data.table(bmr))
```


1. Convert `data.table::data.table()` and `data.frame()` to html tables.


````r
```{r chunk-name, results = 'hide'}
as.data.table(bmr)
```

```{r chunk-name-2, echo = FALSE}
as.data.table(bmr) %>%
  kable(format = "html") %>%
  kable_styling(full_width = TRUE)
```
````

1. Apply a wider [distill layout](https://rstudio.github.io/distill/figures.html) for wide tables.


````r
```{r chunk-name, layout="l-body-outset"}
as.data.table(bmr)
```

```{r chunk-name-2, layout="l-page"}
as.data.table(bmr)
```
````

1. Use a vertical scroll box if the table is too long.

````r
```{r chunk-name-2, echo = FALSE}
as.data.table(bmr) %>%
  kable(format = "html") %>%
  kable_styling(full_width = TRUE) %>%
  kableExtra::scroll_box(height = "400px", extra_css = "border: 0px !important;")
```
````
